# Generated by Django 3.2.6 on 2021-11-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_remove_productmodel_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmodel',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='heightmodel',
            name='height_uz',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='long_description_uz',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='short_description_uz',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='weightmodel',
            name='weight_uz',
        ),
        migrations.RemoveField(
            model_name='widthmodel',
            name='width_uz',
        ),
    ]
