# Generated by Django 3.2.6 on 2021-11-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20211121_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='products', to='products.ProductTagModel', verbose_name='tags'),
        ),
    ]
